# Generated by Django 4.1.7 on 2023-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profassional_status',
            field=models.CharField(choices=[('D', 'Developer'), ('J', 'Junior Developer'), ('S', 'Senior Developer'), ('M', 'Manager'), ('T', 'Student'), ('I', 'Instructor'), ('N', 'Intern'), ('O', 'Other')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
