# Generated by Django 4.1.7 on 2023-04-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_skill_user_profile_userprofile_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Description',
            new_name='description',
        ),
    ]
