# Generated by Django 4.1.7 on 2023-04-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_description_experience_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='University',
            new_name='university',
        ),
    ]
