# Generated by Django 4.1.7 on 2023-04-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_university_education_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepos',
            name='Forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepos',
            name='Stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepos',
            name='Watchers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepos',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
