# Generated by Django 4.1.7 on 2023-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_githubrepos_forks_alter_githubrepos_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(max_length=256),
        ),
    ]
