# Generated by Django 4.1.7 on 2023-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_user_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures\\default_profile_picture.png', upload_to='profile_pictures'),
            preserve_default=False,
        ),
    ]
